name: android-tests
on:
    push:
        branches:
            - master
            - develop
jobs:
    android-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
  
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: 17
                cache: 'gradle'

            - name: Gradle cache
              uses: gradle/gradle-build-action@v2

            # add OpenChargeMaps API key to local.properties          
            - name: Setup local.properties
              working-directory: ./AndroidProject
              env:        
                OCM_API_KEY: ${{ secrets.OCM_API_KEY }}
              run: |
                sed "s/OCM_API_KEY/$OCM_API_KEY/2;" local.defaults.properties > local.properties
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Execute unit tests
            - name: Android units tests
              working-directory: ./AndroidProject
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: ./gradlew clean jacocoTestReport sonarqube
              
            # Show a report of the unit tests results
            - name: Android Test Report
              uses: asadmansr/android-test-report-action@v1.2.0
              if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


    android-instrumentation-tests:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: 17
                cache: 'gradle'
            
            - name: Gradle cache
              uses: gradle/gradle-build-action@v2
            
            # add OpenChargeMaps API key to local.properties          
            - name: Setup local.properties
              working-directory: ./AndroidProject
              env:        
                OCM_API_KEY: ${{ secrets.OCM_API_KEY }}
              run: |
                sed "s/OCM_API_KEY/$OCM_API_KEY/2;" local.defaults.properties > local.properties
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Integration Tests
            - name: Android UI tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 29
                working-directory: ./AndroidProject
                profile: pixel_2
                target: google_apis
                disable-animations: true
                emulator-options: -no-window -gpu off -no-snapshot -noaudio -no-boot-anim
                script: ./gradlew connectedCheck
                
            - name: Android UI tests artifacts
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: ui-tests-artifacts
                path: ./AndroidProject/app/build/reports/androidTests/connected/